# Site settings
title: blog da K4L1
email: kalinathalie@fireshellsecurity.team
description: Some information about dev, infosec and others things
google_analytics: UA-108548581-1
baseurl: ""
url: "https://kalinathalie.github.io/"
author: root

theme: jekyll-theme-hacker

plugins:
  - jekyll-feed
  - jekyll-admin

include: ["_pages"]
exclude:
        - script
        - Gemfile
        - Gemfile.lock
        - jekyll-theme-hacker.gemspec
        - LICENSE
permalink: /:title/ 
