# Site settings
title: FireShell Security Team
email: contact@fireshellsecurity.team
description: The FireShell Security Team is an initiative created in 2017 that aims to disseminate knowledge in the areas of InfoSec, CTFs and Hacking.
google_analytics: UA-108548581-1
baseurl: ""
url: "https://fireshellsecurity.team"
enforce_ssl: fireshellsecurity.team
facebook_username: fireshellst
twitter_username: fireshellst
linkedin_username: fireshell-security-team
instagram_username: fireshellsecurityteam
telegram_username: fireshellnews

disqus:
    shortname: fireshellsecurityteam

plugins:
  - jekyll-feed
  - jekyll-admin
  - jekyll-seo-tag

include: ["_pages"]
exclude:
        - Gemfile
        - Gemfile.lock
        - LICENSE
permalink: /:title/ 

collections:
  authors:
    output: true
    permalink: /:title/
